bool clockwise # Indicates if we should rotate clockwise or counter clockwise
float64 fraction_of_max_angular_velocity # Exists in the interval of (0, 1). Indicates the fraction of the max angular velocity to rotate at. If not in the correct interval, this value is set to 0.5
---
